<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.ciberseguridad</groupId>
  <artifactId>lab-devsecops</artifactId>
  <version>1.0</version>
  <dependencies>
    <!-- Librería vulnerable a Log4Shell (CVE Crítico 10.0) -->
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.14.1</version> 
    </dependency>
  </dependencies>
</project>
