name: DevSecOps Pipeline
on: [push]

jobs:
  sast_semgrep:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Ejecutar SAST (Falla si hay vulnerabilidades)
        run: semgrep scan --config "p/default" --error
